export const columns = [
  {
    field: "id",
    headerName: "ID",
    type: "number",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "registrarId",
    headerName: "Registrar Id",
    type: "number",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    align: "center",
    headerAlign: "center",
  },
  {
    field: "phone",
    headerName: "Phone Number",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "email",
    headerName: "Email",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "address",
    headerName: "Address",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "city",
    headerName: "City",
    flex: 1,
    align: "center",
    headerAlign: "center",
  },
  {
    field: "zipCode",
    headerName: "Zip Code",
    type: "number",
    align: "center",
    headerAlign: "center",
  },
];

export const rows = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@example.com",
    age: 28,
    phone: "+1234567890",
    address: "123 Main St",
    city: "Springfield",
    zipCode: "12345",
    registrarId: 75432,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@example.com",
    age: 34,
    phone: "+1987654321",
    address: "456 Elm St",
    city: "Shelbyville",
    zipCode: "54321",
    registrarId: 86154,
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michaelj@example.com",
    age: 42,
    phone: "+1122334455",
    address: "789 Oak St",
    city: "Capital City",
    zipCode: "67890",
    registrarId: 92048,
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emilyd@example.com",
    age: 27,
    phone: "+1223344556",
    address: "101 Pine St",
    city: "Ogdenville",
    zipCode: "98765",
    registrarId: 48672,
  },
  {
    id: 5,
    name: "David Wilson",
    email: "davidw@example.com",
    age: 30,
    phone: "+1334455667",
    address: "202 Maple St",
    city: "North Haverbrook",
    zipCode: "11223",
    registrarId: 61543,
  },
  {
    id: 6,
    name: "Olivia Brown",
    email: "oliviab@example.com",
    age: 25,
    phone: "+1445566778",
    address: "303 Birch St",
    city: "Brockway",
    zipCode: "33445",
    registrarId: 70986,
  },
  {
    id: 7,
    name: "James Taylor",
    email: "jamest@example.com",
    age: 38,
    phone: "+1556677889",
    address: "404 Cedar St",
    city: "Monorail Town",
    zipCode: "55667",
    registrarId: 83421,
  },
  {
    id: 8,
    name: "Sophia Martinez",
    email: "sophiam@example.com",
    age: 32,
    phone: "+1667788990",
    address: "505 Willow St",
    city: "Cypress Creek",
    zipCode: "77889",
    registrarId: 54231,
  },
  {
    id: 9,
    name: "William Anderson",
    email: "williama@example.com",
    age: 45,
    phone: "+1778899001",
    address: "606 Fir St",
    city: "Springfield",
    zipCode: "99001",
    registrarId: 67890,
  },
  {
    id: 10,
    name: "Isabella Thomas",
    email: "isabellat@example.com",
    age: 29,
    phone: "+1889900112",
    address: "707 Aspen St",
    city: "Shelbyville",
    zipCode: "10112",
    registrarId: 92847,
  },
];
